#!/usr/bin/env bash
# This script install and configure haproxy
apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5508-webs
    bind *:80
    mode http
    balance roundrobin
    server 97741-web-01 100.26.152.57:80 check
    server 97741-web-02 52.201.221.192:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart

